### PR TITLE
Report Bug via SQL

### PR DESCRIPTION
**Pull request by nycholassousa**

### CODE REVIEW

**Comment by icemirow** [comment]
bom trabalho, funcionando 100%, só falta alguém adaptar pro php :)

**Comment by jlcvp** [comment]
@Schiffers, any change in database must be done through the migration system. Modifying the database.sql directly is one of the biggest compatibility problems between the otx and some support systems like gesiorACC

**Comment by mattyx14** [comment]
@ up ... 👍

**Comment by Schiffers** [comment]
@jlcvp ? I do not change anything in DB, the guy that do the PR do it... but you're right, it should be done in migrations

**Pull request closed without merging**
