### PR TITLE
Updating itens & mounts & outfits

### PR DESCRIPTION
**Pull request by favasconcelos**
This will fix: #89 

**Mounts and Outfits from:** https://gitlab.com/guilhermesidney/cliente10/commit/7c17eaeea5fabed97b7ce81680666dafca7ae91a
**Items from:** https://gitlab.com/guilhermesidney/cliente10/commit/9e9554613304ccad63e558328ac587e7cef3b95c

The client used must be the ones from:
- Tibia 11: https://gitlab.com/guilhermesidney/cliente10/tree/master/Tibia%2011.44.5516
- Tibia 10: https://gitlab.com/guilhermesidney/cliente10/tree/master/tibia

### CODE REVIEW

**Comment by Leesneaks** [comment]
I've been editing my server to use the 10.00 client and I've found all sorts of item bugs due to the maps (the one i've been editing for a while and the otxserver map) being made with a otb that has 28594 set as a lever and everything after that is sprite +1.

This also includes the royal stars that are included.
I am missing something? as even testing what you have linked the same issue occurs.
image

**Comment by favasconcelos** [comment]
As far as I tested, using the .otb and tibia that I linked in the commit, only some places are missing a tile, so in order to fix, need to open the map and add the tile.

image

**Comment by Leesneaks** [comment]
> As far as I tested, using the .otb and tibia that I linked in the commit, only some places are missing a tile, so in order to fix, need to open the map and add the tile.
> 
> image

Thanks for your reply.
Are you loading the map thats included in the current commit?

I am using the otb, xml you have pull requested, using the client spr and dat that you have linked and its still bugged out after.

Put items.otb in the path i am using for the items to load and i am still seeing the same map bug, because the map is saved with the items after 28594 changed, .

in the original datapack <item id="28594" article="a" name="dead mummy"/>
and now <item id="28595" article="a" name="dead mummy"/>
because there is now a lever at 28594 in the otb, which then causes every item after to move one place.

for example this should be a reward shrine, but instead is a energy wall

image

and this is the items that have changed.
image

Thanks

lee

**Comment by favasconcelos** [comment]
Thank you for pointing the `itemid=` to `id=`, fixed that.

The other thing is I managed to reproduce what you are saying, what I did was:
- compiled the RME source from here: https://github.com/hjnilsson/rme
- updated the data folder from RME as in: https://gitlab.com/guilhermesidney/cliente10/tree/master/RME/data
- used the map provided (from **master**)
- used the **.spr** and **.data** from the link in commit

Output:
image

I just need to figure out what I did on my windows machine that opened the map as I showed before.

**Comment by favasconcelos** [comment]
@Leesneaks Can you please check now, if it's working?

**Pull request closed without merging**
