### PR TITLE
Update creaturescripts

### PR DESCRIPTION
**Pull request by luanluciano93**

### CODE REVIEW

**Comment by mattyx14** [comment]
This ok :)

**Comment by mattyx14** [comment]
Try create 1 pull request more simple

**Comment by luanluciano93** [comment]
Is it possible to do this only on the web?

**Comment by mattyx14** [comment]
all changes completed?

**Comment by luanluciano93** [comment]
I make the changes through github on the web, I have never downloaded this server. I only do it to help the organization.

**Comment by mattyx14** [comment]
i cancel the pull and i commit your changes ok

**Comment by mattyx14** [comment]
is all?

**Pull request closed without merging**
