### PR TITLE
fixing schema bug

### PR DESCRIPTION
**Pull request by EnzzoCaaue**
fix for #655

### CODE REVIEW

**Comment by mattyx14** [comment]
EnzzoCaaue  and all user i recommend use the [OTX-Database](https://raw.githubusercontent.com/mattyx14/otxserver/otxserv3/path_10_11/schema.sql) and create the correct file migrations v29 with the missing tables required on the this protocol.

**Comment by EnzzoCaaue** [comment]
I don't really know what causes that strange schema bug but this db is the one and only fully working.

**Comment by mattyx14** [comment]
I'm not going to mark this pull request. the reason is that I see changes that I do not know if they are correct for the version of accGesior.

**Comment by EnzzoCaaue** [comment]
In fact, this schema is and old one from this project. Seems to work fine with every gesior I test.

**Pull request closed without merging**
