### PR TITLE
[WIP] Impact Analyzer

### PR DESCRIPTION
**Pull request by jlcvp**
# **DON'T MERGE THIS SHIT BEFORE TESTING** THIS COULD DEBUG 11.40- !

### EN  
Initial implementation of impact analyzer graph. We need to test if it breaks clients older than 11.34 aswell as legacy 10 client

### PT-BR  
Implementação inicial do gráfico do impact analyzer. A gente precisa testar se isso quebra clientes anteriores ao 11.34 ou o 10 legado.

### CODE REVIEW

**Comment by westwol** [comment]
I aprove this changes.

**Comment by malucooo** [comment]
great job Leu!

**Comment by jlcvp** [comment]
did you guys tested it on 11.34- ?

**Comment by westwol** [comment]
It will crash 10.x client for sure so that we need to add a client check before sending impact to client.

**Pull request merged**
