### PR TITLE
Premium scroll gives 250 tibia coins.

### PR DESCRIPTION
**Pull request by jerryb1988**
Modified so scroll gives 250 tibia coins instead of 30 days of premium.

### CODE REVIEW

**Comment by mattyx14** [comment]
This have changes extras no required
Check it for example monsters

**Comment by jerryb1988** [comment]
Fixed so only sends database stuff is isPlayer(), otherwise it just returns true without doing anything.

**Comment by mattyx14** [comment]
Only pull premium changes ...

**Comment by jlcvp** [comment]
This is a custom server modification and shouldn't be a part of the original project. Feel free to implement this on your server though

**Pull request closed without merging**
