### PR TITLE
Update FindMySQL.cmake

### PR DESCRIPTION
**Pull request by viperthepala**
Needed to compile on newer linux versions

### CODE REVIEW

**Comment by jlcvp** [comment]
This would break anyone that doesn't use mariadb, please consider adding backward compatibility instead of a simple overwrite, use c compiler find as an example

**Comment by viperthepala** [comment]
ur wrong, this is exactly how they do it on https://github.com/otland/forgottenserver it adds new functionality to existing one.

**Comment by viperthepala** [comment]
this one looks for eighter mariadb or mysql then installs the other one only looks for mysql.
theres no 3th option as there never was support for WinSQL/Oracle/Postgresql

**Comment by viperthepala** [comment]
but always good to see a instant close rather then a discussion formed

**Pull request closed without merging**
