### PR TITLE
Explorer Society 100% and others

### PR DESCRIPTION
**Pull request by OBUCHpl**
-- Map
- map cleanup
- added offline training statues in Kazordoon
- Explorer Society: added Ulderek's Rock chest (orc powder mission), icicle fix (Folda, ice delivery mission), family brooch fix (Dwacatra, pickaxe mission), removed chest between Thais and Fibula (easily inflammable sulphur, instead you need to use spoon on lava hole - like RL)
- can't upload files to GitHub bigger than 25MB, so here is the link:
http://www.mediafire.com/file/jouyieciqegb5co/realmap.zip

-- Explorer Society quest
- a lot lot lot of fixes, now quest is fully working
- added quest-doors
- Angus/Mortimer fix, removed "Island of Dragons" and "Ice Music" quests
- Lurik fix, added "Island of Dragons" and "Ice Music" quests from Angus/Mortimer
- added teleports: Port Hope-Northport and Svargrond-Liberty Bay
- ability to using teleport PH-NP and Svar-LB only after completing E.S. quest
- fixed butterfly container, botanist container, ectoplasm container etc.

-- What a foolish quest - still work in progress
- spoon and kitchen knife (mission 1 and 8 fix)

-- Questlog
- Explorer Society full questlog
- Budrik's minotaur task fix

-- Monsters
- Slime corpse fix (now it decays)
- Feverish Citizen loot fix (stuffed toad instead plague mask/bell)
- butterflies corpse fix (for Explorer Society Quest)

-- NPC
- Nilsor misspelling, fine sulphur itemID fix
- Buddel travels only after completing Barbarian Test
- Captain Max fix, now it's possible to buy and sell HotD

-- Other
- griffinclaw flower fix, griffinclaw globalevent unlocked
- items.xml small fix
- Inq quest rewarddoor.lua misspelling

### CODE REVIEW

**Comment by malucooo** [comment]
@igordelecrode check the map... the scripts are fine, but the map i haven't checked!

**Comment by igordelecrode** [comment]
@malucooo I will check the map and as soon as I finish returning.

**Comment by malucooo** [comment]
wrong loot in feverist citizen... ¬¬

**Comment by OBUCHpl** [comment]
need to do some re-work

**Pull request closed without merging**
