### PR TITLE
attempt to solve #334

### PR DESCRIPTION
**Pull request by mattyx14**
Marge last

### CODE REVIEW

**Comment by jlcvp** [comment]
guys, DON'T MERGE this branch with master, we need to test it before.

**Comment by mattyx14** [comment]
Ok

**Comment by Olimpotibia** [comment]
Not work i tested no errors on console but server crash when u try to put item on equip.

https://github.com/Olimpotibia/RTS/tree/Test

**Comment by jlcvp** [comment]
Ok, I'll try to adress this later today, I'm at work right now.

**Comment by darkjav** [comment]
Yes, for me also crashed.

**Pull request closed without merging**
